version: '3.8'

services:
  football-mixer:
    container_name: football-mixer-backend
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=manage.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    command: flask run --host=0.0.0.0 --debug